/* eslint-disable */
/* This file is generated by scripts/generate-application-loaders.mjs */

import type { NativeApplicationEntry } from "@/platform/sdk/native-application-contract";

export const applicationLoaderManifest: Record<
  string,
  () => Promise<{ applicationEntry: NativeApplicationEntry }>
> = {
  "battery-efficiency": () => import("@/applications/battery-efficiency/entry"),
  "overview": () => import("@/applications/overview/entry"),
  "planning": () => import("@/applications/planning/entry"),
  "sources": () => import("@/applications/sources/entry"),
  "telemetry": () => import("@/applications/telemetry/entry"),
};
