/* This file is generated by scripts/generate-application-loaders.mjs */

import type { NativeApplicationEntry } from "@/platform/sdk/native-application-contract";

export const applicationLoaderManifest: Record<
  string,
  () => Promise<{ applicationEntry: NativeApplicationEntry }>
> = {
  "ai-engineer": () => import("@/applications/ai-engineer/entry"),
  "control-panel": () => import("@/applications/control-panel/entry"),
  "knowledge": () => import("@/applications/knowledge/entry"),
  "overview": () => import("@/applications/overview/entry"),
  "planning": () => import("@/applications/planning/entry"),
  "telemetry": () => import("@/applications/telemetry/entry"),
};
