export const queryKeys = {
  feedStatus: (sourceId: string) => ["feed-status", sourceId] as const,
  watchlist: (sourceId: string) => ["watchlist", sourceId] as const,
  telemetryList: (sourceId: string) => ["telemetry-list", sourceId] as const,
  telemetryInventory: (sourceId: string) => ["telemetry-inventory", sourceId] as const,
  telemetrySources: ["telemetry-sources"] as const,
  vehicleConfigs: ["vehicle-configs"] as const,
  vehicleConfig: (path: string) => ["vehicle-config", path] as const,
  aiEngineerModelConfig: ["ai-engineer-model-config"] as const,
  aiEngineerConversations: ["ai-engineer-conversations"] as const,
  aiEngineerConversation: (conversationId: string) => ["ai-engineer-conversation", conversationId] as const,
  aiEngineerModels: ["ai-engineer-models"] as const,
  knowledgeDocuments: ["knowledge-documents"] as const,
  deploymentOverview: ["deployment-overview"] as const,
  activeFrontendPreviewRuntime: ["active-frontend-preview-runtime"] as const,
  codeRepositoryStatus: (root: string, branch: string) => ["code-repository-status", root, branch] as const,
  telemetrySourceRuns: (sourceId: string) => ["telemetry-source-runs", sourceId] as const,
  telemetryChannelRuns: (channelName: string, sourceId: string) =>
    ["telemetry-channel-runs", channelName, sourceId] as const,
  telemetrySearch: (params: Record<string, string>) => ["telemetry-search", params] as const,
  telemetryExplanation: (channelName: string, sourceId: string, scopeKey = "") =>
    ["telemetry-explanation", channelName, sourceId, scopeKey] as const,
  telemetryRecent: (params: Record<string, string>) => ["telemetry-recent", params] as const,
  telemetrySourcesStatus: (sourceId: string) => ["simulator-status", sourceId] as const,
  sourceObservations: (sourceId: string, limit: number) => ["source-observations", sourceId, limit] as const,
  telemetryEvents: (params: Record<string, string> | string) => ["ops-events", params] as const,
  subsystems: (sourceId: string) => ["telemetry-subsystems", sourceId] as const,
  units: (sourceId: string) => ["telemetry-units", sourceId] as const,
} as const;
